name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main  # main branch push olunca deploy et

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular
      run: npm run build --prod

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Save PEM key
      run: |
        echo "${{ secrets.EC2_KEY }}" > mykey.pem
        chmod 400 mykey.pem

    - name: Copy Docker image to EC2
      run: |
        docker save myapp:latest | bzip2 | ssh -o StrictHostKeyChecking=no -i mykey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bunzip2 | docker load'

    - name: Run container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i mykey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
        "docker stop myapp || true && docker rm myapp || true && docker run -d --name myapp -p 80:80 myapp:latest"
