name: Deploy Angular to EC2

on:
  push:
    branches:
      - main   # veya kendi branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/<repo>
            git pull origin main
            docker build -t my-angular-app .
            docker stop my-angular-app || true
            docker rm my-angular-app || true
            docker run -d -p 80:80 --name my-angular-app my-angular-app
          EOF
