name: CI/CD - Angular Docker Build

# 1. Ne zaman çalışacak?
on:
  push:
    branches:
      - main # Sadece main dalına yapılan push işlemlerinde çalışır

# 2. İş Tanımı
jobs:
  build_and_deploy:
   
    runs-on: [self-hosted] 

    steps:
      - name: Runner Durumu Kontrolü
        run: echo "İşlem EC2 Self-Hosted Runner üzerinde başlatılıyor..."

      # 3. Kodu çekme
      - name: Kodu Çekme
        uses: actions/checkout@v4

      # 4. Docker İmajını Oluşturma
      - name: Docker Imajını Build Etme
        # Build ve tag işlemini gerçekleştirir
        run: |
          docker build -t angular-app:latest .
          echo "Docker imajı başarıyla oluşturuldu: angular-app:latest"

      # 5. Mevcut Konteyneri Durdurma ve Silme (Önceki Sürüm Varsa)
      - name: Eski Konteyneri Temizleme
        run: |
          # Eğer konteyner çalışıyorsa durdur
          docker stop angular-app-live || true 
          # Durdurulan konteyneri sil
          docker rm angular-app-live || true 
        # || true, hata verse bile (konteyner yoksa) pipeline'ın devam etmesini sağlar

      # 6. Yeni Imajı Çalıştırma
      - name: Yeni Konteyneri Çalıştırma ve Yayınlama
        run: |
          docker run -d \
            --name angular-app-live \
            -p 80:80 \
            angular-app:latest
          echo "Uygulama başarıyla 80. portta başlatıldı."
